### ISSUE TITLE
Podatki s spleta

### ISSUE THREAD

**Issue by jaanos** [Anchiqua/APPR-2015-16#1]
Stran, ki si jo poskušala uvoziti, dobi podatke od tukaj:

http://www.nhl.com/stats/rest/grouped/skaters/season/skatersummary?cayenneExp=seasonId=20142015%20and%20gameTypeId=2

Podatki so v obliki JSON, ki ste jo omenili na predavanjih. Za uvoz boš potrebovala knjižnico `jsonlite`, za primer uvoza pa si poglej [program s predavanj](https://github.com/alenFMF/APPR-15-16/blob/master/06_Podatki_na_spletu/viri/web.r) (četrti primer).

**Comment by Anchiqua** [comment]
ali lahko uporabim za vizualizacijo poleg ggplot2 tudi plotly?

**Comment by Anchiqua** [comment]
zanima me tudi kako ste našli stran, kjer sem lahko uvozila podatke, ker bi še nekaj uvozila (http://www.nhl.com/stats/player?reportType=season&report=bios&season=20142015&gameType=2&sort=playerBirthDate&aggregate=1&pos=S) vendar ne najdem tabele.

**Comment by jaanos** [comment]
Za vizualizacijo lahko seveda uporabiš tudi plotly.

Kar se podatkov tiče, moram priznati, da sem pogoljufal in z Wiresharkom pogledal, kakšne poizvedbe dela brskalnik (obstajajo tudi vtičniki za brskalnike, ki počnejo točno to). Izgleda sicer, da je vir podatkov spet isti - na strani so le prikazani v drugačnem vrstnem redu.

**Comment by Anchiqua** [comment]
Vir je isti, vendar so podatki drugačni, ker vsebujejo druge podatke. A je kakšna možnost, da bi lahko še kako drugače prišla do teh podatkov?

**Comment by jaanos** [comment]
Aha, vidim, da so podatki še tukaj:

http://www.nhl.com/stats/rest/individual/skaters/season/bios?cayenneExp=seasonId=20142015%20and%20gameTypeId=2

**Comment by Anchiqua** [comment]
ali bi mi lahko ponovno povedali kako ste mi odstranili vsa opozorila, ko pretvarjam v pdf?
Pri grafih mi vedno eno in isto opozorilo napiše in nevem kaj to pomeni...

**Comment by Anchiqua** [comment]
A je možno da rabim doma imeti latex da pretvorim v pdf datoteko?

**Comment by jaanos** [comment]
Da ti v poročilo ne bo izpisovalo obvestil ob uvozu knjižnic, vse klice ukazov `library` in `require` premakni iz `uvoz/uvoz.r` v `lib/libraries.r`. Druga možnost bi bila, da pri bloku, kjer kličeš `uvoz.r`, nastaviš `results='hide'` in `message=FALSE`, da se ta obvestila ne izpisujejo.

Poročila ti sicer trenutno ne prevede, ker se sklicuješ na neobstoječo spremenljivko `p` - tam najbrž želiš kakega od grafov, ki si jih narisala v `uvod.r`.

Za prevajanje v PDF potrebuješ LaTeX. Svetujem, da si ga namestiš, da točno vidiš, kako bo poročilo izgledalo; do takrat pa lahko prevajaš tudi v HTML.

**Comment by Anchiqua** [comment]
Pri grafih mi še vedno napiše: Non Lab interpolation is deprecated , čeprav mi ga pokaže ampak se na HTML vidi napis

**Comment by jaanos** [comment]
V zadnjem commitu imaš v poročilu vrstice, kot so

``````
```print(slika1)```
``````

Če hočeš, da se ti graf dejansko pokaže, bo treba narediti blok kode:

``````
```{r graf1, echo=FALSE, message=FALSE, warning=FALSE}
print(slika1)
```
``````

Tako tudi ne bi smelo izpisovati sporočil in opozoril.

Pri uvažanju knjižnic dobiš opozorilo, da nalaganje knjižnici plyr za knjižnico dplyr lahko povzroči probleme. Zato bo najbolje, če odstraniš klic `require(plyr)` (tako v `uvoz.r` kot v `libraries.r`).

Meni sicer ne izpisuje grafov, narejenih s plotly. Katero različico plotly imaš? To lahko preveriš z ukazom `packageVersion("plotly")`. Meni izpiše `2.0.16`.

**Comment by Anchiqua** [comment]
Za plotly mi napiše, da imam verzijo 2.0.3 in mi tudi ni pokazalo na HTML, vendar mi v Rstudio normalno pokaže. A je kakšna možnost da bi se mi videli grafi od plotly?

**Comment by jaanos** [comment]
Glede na to, da nama obema ne deluje, svetujem, da zaenkrat grafov s plotly ne prikazuješ, in vključiš samo tiste z ggplot2.

Glede na to, da ti poročilo prevede, bom dodal povezavo na tvoj projekt (čeprav zaenkrat še ni grafov v poročilu). Prosim javi mi, če boš še kaj spreminjala, da posodobim povezavo.

**Comment by Anchiqua** [comment]
Ok. Bom zdaj popravla pa dala na GIT.

**Comment by Anchiqua** [comment]
Danes sem delala analizo podatkov in bi rada naredila graf, kjer bi uporabila geom_bar in bi imela le dva pravokotnika, ki kažeta vsoto vseh točk različnih skupin. Naredila sem dve tabeli skupini a in b, vendar sem posebej naredila vsoti in nevem kako bi naredila tak graf. Vse sem shranila pod vizualizacijo.

**Comment by jaanos** [comment]
Graf lahko narediš nekako tako:

``` R
ggplot(točke %>% group_by(polletje = ifelse(mesec.rojstva < 7, "H1", "H2")) %>%
         summarise(točke = sum(točke)), aes(x = polletje, y = točke)) +
  geom_bar(stat = "identity")
```

Z `group_by` združiš podatke po določenem kriteriju - v tem primeru glede na polletji, ki sem ju poimenoval `"H1"` in `"H2"` - seveda lahko uporabiš tudi drugačne oznake. Potem s `summarise` izračunaš vsoto točk v vsaki od teh skupin.
