### ISSUE TITLE
zemljevid

### ISSUE THREAD

**Issue by Anchiqua** [Anchiqua/APPR-2015-16#2]
Zanima me, kaj je imenski podatek pri zemljevidu, ker jaz imam le številskega?

**Comment by Anchiqua** [comment]
V šoli sem naredila zemljevid, vendar mi doma ga noče prikazat in napiše:
 Error in paste0(map, "/", pot.zemljevida) : 
  argument "pot.zemljevida" is missing, with no default
kaj to pomeni?

**Comment by jaanos** [comment]
Trenutno se ti program ustavi v `vizualizacija.r`, saj ti manjka funkcija [`pretvori.zemljevid`](https://gist.github.com/jaanos/841499a08ceece11bdbf). Morda bo najbolje, da si jo skopiraš kar v `lib/uvozi.zemljevid.r`. Če jo dodam, se mi zemljevid lepo izriše. Napaka sicer kaže na to, da naj bi manjkal drugi parameter pri funkciji `uvozi.zemljevid`. Preveri, ali si morda kaj spremenila glede na zadnji commit na GitHubu.

Kar se tiče imenskih podatkov, izgleda, da je edini, ki ga imaš, igralni položaj. Če se ti ne zdi smiselno, morda tega ni potrebno prikazovati na zemljevidu.

Še to: trenutno ti bo `right_join` pri risanju zemljevida izpisal opozorilo, ker imaš v stolpcu `drzava` razpredelnice `tabela2` nize, v zemljevidu pa je stolpec `adm0_a3` faktor. Da se znebiš opozorila, lahko pred risanjem zemljevida tudi stolpec `drzava` pretvoriš v faktor z ustreznimi vrednostmi:

``` R
tabela2$drzava <- factor(tabela2$drzava, levels = levels(svet$adm0_a3))
```

**Comment by Anchiqua** [comment]
Dodala sem funkcijo pretvori.zemljevid in mi dela. Ali bi lahko za imenske podatke dala 8 najboljših igralcev sezone? Da bi za imenski podatek dala njihovo ime?

**Comment by jaanos** [comment]
Ne vem, kako bi to prikazala na zemljevidu. Lahko pa seveda narediš kak graf, kjer primerjaš njihove statistike.

**Comment by Anchiqua** [comment]
Bom raje še kakšen zemljevid s številskimi podatki dodala. Ali lahko dam v poročilo tudi tabelo z eno vrstico? Mislim, da mi zaradi tega noče pretvoriti poročila v HTML.

**Comment by jaanos** [comment]
Lahko - če je to problem, potem morda raje podatke iz te tabele napiši kar v besedilo (če jih ni preveč).

**Comment by jaanos** [comment]
Poročila ti sicer ne prevede zaradi napake pri grafu `slika10` - v razpredelnici `tabela` imaš stolpec `visina`, v `povprecja` pa `višina`, tako da bo treba popraviti:

``` R
slika10 <- ggplot(tabela, aes(x = igralci, y=visina)) + geom_point(aes(colour=visina)) +
  scale_colour_gradient2(low = "khaki1", mid = "sienna1",high = "lightsalmon4", midpoint = povprecja$višina) + 
  geom_hline(data=povprecja, aes(yintercept=višina))
```

Seveda ne pozabi v poročilu poklicati še programa `vizualizacija/vizualizacija.r` ter izrisati grafov in zemljevidov, ki jih tam narediš. Če se hočeš sklicevati na grafe (deluje samo v PDF), bloku z grafi dodaj parametra `fig.cap` z napisom pod grafom in `fig.align` s poravnavo (npr. `fig.align = 'center'`) - podobno kot v vzorcu.

**Comment by Anchiqua** [comment]
Šumnike sem zdaj popravila, vendar je nova napaka. Ali je možno, da bi naredila podobno tabelo kot je tabela2, vendar bi namesto števila igralcev izračunala vsoto točk od vseh igralcev iz ene države za vsako državo posebej. Tako, da bi naredila še en zemljevid.

**Comment by jaanos** [comment]
Pri `slika6` in `slika10` se še sklicuješ na `povprecja$točke` oziroma `povprecja$višina`. Potem imaš še problem z bloki kode, kjer hočeš izpisati razpredelnici `prvipovprecja` in `drugipovprecja`. Ker ju imaš definirani v `vizualizacija.r`, bo najprej treba vključiti ta program:

``````
```{r vizualizacija, echo=FALSE, message=FALSE}
source("vizualizacija/vizualizacija.r", encoding = "UTF-8")
```
``````

Potem lahko izpišeš razpredelnici - seveda v ustrezno oblikovanem bloku, npr.

``````
```{r povprecja, echo=FALSE}
kable(head(prvipovprecja))
kable(head(drugipovprecja))
```
``````

Podobno naredi tudi pri razpredelnici `podatki2`. Zadnji problem je še v `vizualizacija.r`, kjer se v vrstici 57 sklicuješ na spremenljivko `točke` - najbrž hočeš tam `tocke`.

Če hočeš izračunati vsoto točk po državah, si podobno kot pri polletju pomagaš z `group_by` in `summarise`:

``` R
tocke %>% group_by(drzava) %>% summarise(tocke = sum(tocke))
```

**Comment by Anchiqua** [comment]
Pri poročilu sem vse popravila in še vedno piše da je napaka.

**Comment by jaanos** [comment]
Tvoj program očitno porabi preveč pomnilnika. Da zmanjšaš količino porabljenega pomnilnika, svetujem sledeče:
- Izrisovanje grafov premakni v poročilo. Namesto, da v `uvoz.r` in `vizualizacija.r` grafe shraniš v spremenljivko, izvedi ustrezne ukaze (brez shranjevanja v spremenljivko) namesto ukazov `print` v poročilu. V `uvoz.r` zakomentiraj tudi grafe, ki jih narišeš s plotly, iz `vizualizacija.r` pa pobriši oba ukaza `plot`.
- Pri vsakem zemljevidu kličeš `pretovri.zemljevid` in rezultat shraniš v novo spremenljivko. Ker je zemljevid obakrat enak, lahko to narediš samo enkrat (shraniš npr. v `sv`) in dobljeno razpredelnico uporabiš pri risanju obeh zemljevidov.
- Grafi s podatki o igralcih so nepregledni, tako da svetujem, da izbereš neko manjšo množico igralcev in podatke prikažeš samo zanje. Poleg tega bo stolpčni diagram (`geom_bar` s parametrom `stat = "identity"`) bolj primeren kot točkovni graf.
- Uporabi manj natančen zemljevid, ki ga dobiš na http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip (pri `uvozi.zemljevid` za drugi parameter podaj `"ne_110m_admin_0_countries"`). Ta ima iste stolpce kot zemljevid, ki ga trenutno uporabljaš, tako da drugega ne bo potrebno spreminjati.

Pri prvem grafu se je očitno nekje izgubilo štetje igralcev po državah. Tako bo v redu:

``` R
ggplot() + geom_polygon(data=tabela2 %>% group_by(drzava) %>%
                          summarise(stevilo = length(igralci)) %>%
                          right_join(sv, c("drzava" = "adm0_a3")), 
                               aes(x=long, y=lat, group=group, fill=stevilo),
                               color="grey") + 
                                 scale_fill_continuous(low="#69b8f6", high="#142d45") +
                                 xlab("") + ylab("")
```
