### ISSUE TITLE
4. faza

### ISSUE THREAD

**Issue by Anchiqua** [Anchiqua/APPR-2015-16#3]
Zanima me, kaj bi lahko naredila za 4.fazo. Ali lahko naredim kakšno raziskavo iz podatkov, ki jih imam, ker mislim da bi bilo preveč podatkov in tabel, če bi jih uvozila za par let nazaj.

**Comment by jaanos** [comment]
Seveda, če imaš podatkov dovolj, ti ni potrebno uvažati drugih. Zagotovo lahko v obstoječih podatkih najdeš kakšne zanimive korelacije, ali pa npr. igralce razdeliš na skupine. Če bi imela podatke za prejšnja leta, bi sicer imela še časovno komponento, tako da bi lahko poiskala še kakšne trende.

**Comment by Anchiqua** [comment]
Kako pa bi lahko razdelila igralce v skupine?

**Comment by jaanos** [comment]
Razvrščanje v skupine glede na podobnost lahko delaš npr. z metodo k-means, ki smo si jo pogledali na vajah, ali pa s hierarhičnim razvrščanjem, ki ste ga omenili na predavanjih.

**Comment by Anchiqua** [comment]
Rada bi uporabila kmeans vendar, če bi hotela pokazati na zemljevidu bi morala razporediti države v skupine? Tabele imam narejene za igralce in bi bilo lažje delati s tem, da bi pogledala npr. 5 skupin in primerjala točke z procentom strela ali pa točke in odigrane tekme. Za države imam narejeni le tabeli, kjer imam prikazano število igralcev iz določene države in skupen seštevek točk za države. Ali bi lahko kaj iz tega naredila?

**Comment by Anchiqua** [comment]
Uporabila sem funkcijo kmeans za države, ki sem jih razdelila v 5 skupin glede na točke in število igralcev, vendar mi ne prikaže zemljevida.

**Comment by jaanos** [comment]
Najprej, program se ti ustavi na koncu programa `uvoz.r`, ko prvič definiraš `tabela3`, saj spremenljivka `tocke` ne obstaja. Glede na to, da takoj za tem pravilno definiraš to razpredelnico, je najbrž ta vrstica odveč.

Da boš lahko iz podatkov risala zemljevid, bo potrebno najprej imena držav ohraniti kot imena vrstic v podatkih, na katerih delaš razvrščanje. Najlažje to narediš tako, da prepišeš stolpec `drzava` v imena vrstic, nato pa ga pri skaliranju izpustiš:

``` R
tabela4 <- inner_join(tabela3, tabela2)
rownames(tabela4) <- tabela4$drzava
tabela4.norm <- tabela4 %>% select(-drzava) %>% scale()
```

Ker imaš za države tričrkovne kratice, bo potrebno ujemanje narediti s stolpcem `adm0_a3` v zemljevidu:

``` R
tabela4.skupine <- data.frame(Drzava = factor(names(k$cluster),
                                              levels = svet$adm0_a3),
                               skupina = factor(k$cluster))

ggplot(tabela4.skupine %>% right_join(sv, by = c("Drzava" = "adm0_a3")),
       aes(x=long, y=lat, group=group, fill=skupina)) +
  geom_polygon(color="grey")
```

Parameter `levels` pri stolpcu `Drzava` je potreben, da se `right_join` ne pritoži, da gre za različne faktorje.

Seveda pa ni nujno, da razvrščaš države v skupine - precej več podatkov imaš za igralce, in ti so tudi bolj neposredno primerljivi. Razvrstitev igralcev lahko pokažeš npr. na točkovnem grafu, ki prikazuje dve spremenljivki (po možnosti taki, da je lepo vidna delitev); morda lahko potem v vsaki skupini izpostaviš kakega igralca (npr. izpišeš njegovo ime zraven njegove točke).

**Comment by Anchiqua** [comment]
Naredila sem skupine za igralce, vendar imam pri grafu težave  z poimenovanjem x in y-osi, ker če uporabim tabelo, kjer imam igralce razporejene v skupine, mi npr. ne najde procenta strela.

**Comment by jaanos** [comment]
Sklepam, da gre tukaj za graf `slika13`. Ker ga rišeš iz razpredelnice `tabela5.skupine`, v to vključi vse podatke iz `tabela5`:

``` R
tabela5.skupine <- data.frame(tabela5, skupina = factor(k2$cluster))
```

Potem lahko narišeš želeni graf, pri čemer skupino prikažeš npr. z barvo:

``` R
slika13 <- ggplot(tabela5.skupine,
                  aes(x=tocke, y=procent.strela, color=skupina)) + geom_point()
```
