### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by Anchiqua** [Anchiqua/APPR-2015-16#4]
V kateri datoteki se naredi shiny? Meni se niti osnovno okence noče prikazati, kaj bi lahko bila težava?

**Comment by jaanos** [comment]
Za shiny sta predvideni datoteki v mapi `shiny` - tam si sicer pobrisala vsebino iz vzorca, po katerem se lahko zgleduješ.

Glede na to, da ti niti osnovnega okna ne odpre, boš morda morala še namestiti knjižnico shiny (to storiš enako kot za druge knjižnice pod _Tools_ / _Install Packages..._).

**Comment by Anchiqua** [comment]
Naredila sem za shiny, vendar je nekje napaka, ker mi ne zažene programa.  Ali je narobe, če sem vse shranila le pod eno datoteko?

**Comment by jaanos** [comment]
Načeloma ni narobe, če je ves program v eni datoteki - tu gre predvsem za ločitev funkcionalnosti od postavitve.

Sicer pa zadnje različice očitno še nisi naložila na GitHub, tako da težko komentiram, kje se zalomi.

**Comment by Anchiqua** [comment]
Zdaj je gor zadnja različica na datoteki server.R.

**Comment by jaanos** [comment]
Shiny ti ne deluje, ker nikjer ne dobi podatkov iz tvojega programa. Najbolje bo, če narediš tako:
- V `shiny.R` naj bo

``` R
library(shiny)

source("lib/libraries.r", encoding = "UTF-8")
source("uvoz/uvoz.r", encoding = "UTF-8")

runApp("shiny")
```

Po potrebi lahko seveda dodaš še druge ukaze `source`. Ta program uporabljaš za samostojno poganjanje Shinyja - pri vključevanju v poročilo bodo ustrezni `source` že narejeni.
- V `ui.R` premakni spremenljivko `fluidPage` iz `server.R` - ni je potrebno shranjevati v spremenljivko, pač pa enostavno začneš s `fluidPage(...`.
- V `server.R` pusti funkcijo, ki je spet ni treba shranjevati v spremenljivko.

Da ti bo graf prikazalo, se mora njegovo ime iz `server.R` ujemati s tistim v `ui.R` - v prvem imaš `plot1`, tako da isto ime uporabi namesto `"kmeans"`. Seveda ti bo graf deloval samo za številske stolpce. Če hočeš dobiti samo številske stolpce, lahko to narediš z

``` R
names(tabela)[lapply(tabela, is.numeric) %>% unlist()]
```

**Comment by jaanos** [comment]
Še to: v #3 sem te opozoril na napako na koncu `uvoz.r`, ki jo bo treba popraviti, da ti bo tudi Shiny deloval.

**Comment by Anchiqua** [comment]
Shiny sem popravila in mi kaže novo težavo : 
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection

Kako lahko to popravim?

**Comment by jaanos** [comment]
Preberi si še enkrat moj zgornji komentar - naj torej ne bo vse v `server.R`. Ko premakneš ustrezne dele v `shiny.r` in `ui.R`, pobriši še vrstico `shinyApp(ui=ui, server = server)`.

**Comment by Anchiqua** [comment]
Kodo sem zdaj premaknila tudi v drugi dve datoteki, vendar mi isti problem pokaže:
`Warning in file(filename, "r", encoding = encoding) :
  cannot open file 'lib/libraries.r': No such file or directory
Warning: Error in file: cannot open the connection
Stack trace (innermost first):
    40: file
    39: source
    38: source
     1: shiny::runApp
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection`

**Comment by jaanos** [comment]
Odstrani še ukaze `source` in `runApp("shiny")` iz `server.R`.

**Comment by Anchiqua** [comment]
Hvala, zdaj mi dela. Zanima me kaj je razlika med `geom_smooth(method="loess")` in `geom_smooth(method="lm")`. Meni vsaka metoda drugače nariše krivuljo in potem pridem do različnih rezultatov.
