### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by Anchiqua** [Anchiqua/APPR-2015-16#5]
Projekt sem zaključila, vendar mi napačno izpiše tabelo 2 in tabelo 3 pri uvozu. Kode nisem spreminjala, ampak imam zdaj tabeli veliki 1x1.

**Comment by jaanos** [comment]
Poročila ti ne prevede - v `analiza.r` imaš odvečno vrstico `table(k$cluster)`. Glede na to, da imaš Shiny aplikacijo v mapi `shiny`, to tudi podaj pri `shinyAppDir` (namesto `"analiza"`). Da ti bo ta ukaz sploh deloval, v `libraries.r` dodaj še `library(shiny)`.

Ko sam poženem, imata `tabela2` in `tabela3` vsaka po 20 vrstic in 2 stolpca. Morda je bilo kaj narobe s podatkovnim virom, pa se je sedaj uredilo.

Še to: v glavi poročila imaš vrstico `runtime: shiny`, ki pa je zamaknjena in tako nima učinka - pri prevajanju te bo RStudio vprašal, ali želiš pognati Shiny. Če pobrišeš presledka pred to vrstico, se bo vsakič samodejno pognal Shiny.

Še ena vsebinska pripomba: v Shiny aplikaciji rišeš graf glede na izbrani spremenljivki, obenem pa narediš delitev na skupine, pri čemer upoštevaš samo ti dve spremenljivki. Rezultat je seveda ta, da bo vsakič prišlo do neke "lepe" delitve, ki pa kot taka nima globljega pomena. Bolj zanimivo bi bilo, če delitev poračunaš vnaprej in pri tem uporabiš vse spremenljivke, potem pa bi na grafu za izbrani spremenljivki prikazala to delitev. Ta seveda ne bo vedno tako lepa, bi pa zato bilo zanimivo videti, za katere pare spremenljivk je ta delitev smiselna - torej, katere spremenljivke na nek način "karakterizirajo" posamezno skupino.

**Comment by Anchiqua** [comment]
Naredila sem novo tabelo7 v `analiza.r` kjer sem naredila delitev z vsemi spremenljivkami in sem jo dodala v `server.R`. Nevem pa, če je pravilno, ker imam v shiny-ju še vedno lepo delitev.

**Comment by jaanos** [comment]
Namesto iz `selectedData()` naredi `kmeans` na `tabela7.norm`, da bo razvrščanje upoštevalo vse stolpce.

**Comment by Anchiqua** [comment]
Popravila sem shiny in se vidijo spremembe. Ko zaženem poročilo mi ponovno kaže napako, ki je ne najdem.

**Comment by jaanos** [comment]
Kje pa dobivaš napake? Edina stvar, ki jo opazim, je opozorilo za naslovom _Analiza in vizualizacija podatkov_ - dodaj parameter `warning=FALSE` k bloku kode, kjer kličeš `vizualizacija.r`, da se znebiš tega opozorila.

Glede na to, da mi deluje, bom dodal povezavo na repozitorij za zagovore. Profesorju lahko javiš, da si projekt dokončala, da se domenita za termin zagovora.

**Comment by Anchiqua** [comment]
Napiše mi da je v vrstici 138. 

Ok.

**Comment by jaanos** [comment]
Parameter dodaš v glavo bloka:

``````
```{r vizualizacija, echo=FALSE, message=FALSE, warning=FALSE}
source("vizualizacija/vizualizacija.r", encoding = "UTF-8")
```
``````
